package main

import (
	"strings"

	"6.5840/mr"
)

// The map function is called once for each file of input. The first
// argument is the name of the input file, and the second is the
// file's complete contents. You should ignore the input file name,
// and look only at the contents argument. The return value is a slice
// of key/value pairs.
func Map(filename string, contents string) []mr.KeyValue {
	word := "A"
	sentences := strings.Split(contents, "\n")

	kva := []mr.KeyValue{}
	for _, s := range sentences {
		if strings.Contains(s, word) && len(s) > 1 {
			kv := mr.KeyValue{s, "1"}
			kva = append(kva, kv)
		}
	}
	return kva
}

// The reduce function is called once for each key generated by the
// map tasks, with a list of all the values created for that key by
// any map task.
func Reduce(key string, values []string) string {
	// return the number of occurrences of this word.
	return key
}
